# Generated by Django 3.1.7 on 2021-02-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
